### ISSUE TITLE
Add new datasets from https://github.com/dariusk/corpora to rcorpora

### ISSUE THREAD

**Issue by spsaaibi** [gaborcsardi/rcorpora#1]
@gaborcsardi Some new datasets have been added to https://github.com/dariusk/corpora. I wanted to be able to access them using `rcorpora` from R. Therefore, I copied the content of https://github.com/dariusk/corpora/tree/master/data into the data path, and verified the package was built correctly. I also re-ran `readme.Rmd` to reflect these changes.

The fork that contains these changes can be found: https://github.com/spsaaibi/rcorpora. Let me know if you would consider these in a PR for `rcorpora`.

**Comment by gaborcsardi** [comment]
Thanks, yes, I don't mind updating the package, I did it already once or twice, and you are right, that it is time for another update.

My repo is actually a fork of the original one, and I usually update by `git merge`, and then move some files around and fix non-clean merges.

One thing that looks new in the original repo is that there are two-level hierarchies, so the R commands for generating the manual might need updates.

Another thing is that I don't have a README.html, only an Rmd and an md. I usually just run `make` to update the README, or `touch README.Rmd; make`. I understand that this might not work on all systems.

So I think it is simplest if I just update manually now, will try in a minute.

**Comment by gaborcsardi** [comment]
Yes, it seems like `categories()` only works at the top level. It would be great to browse subcategories as well.

**Comment by gaborcsardi** [comment]
Although `corpora()` lists everything.

**Comment by gaborcsardi** [comment]
OK, I updated, and submitted 1.2.0 to CRAN. Thanks for the heads up!

**Comment by spsaaibi** [comment]
Thank you so much!, this is great :), Cheers!

Sebastian Perez Saaibi

On Sun, May 01, 2016 at 23:09 "Gábor Csárdi"

<
mailto:

> wrote:

OK, I updated, and submitted 1.2.0 to CRAN. Thanks for the heads up!
