### ISSUE TITLE
corpora encoding

### ISSUE THREAD

**Issue by vrkrv** [gaborcsardi/rcorpora#3]
**corpora**  returns wrong encoding.
I use R 3.3.1 under Windows x64 and **readLines** returns incorrect encoding.
call:

> rcorpora::corpora("words/stopwords/ru")

I think it would be great if encoding will be explicitly chosen inside **corpora** function:

> fromJSON(readLines(filename, warn = FALSE, **encoding = "UTF-8"**))

**Comment by gaborcsardi** [comment]
:+1: Would you mind submitting a PR?

**Comment by isteves** [comment]
As far as I can tell, removing `readLines` completely also fixes the encoding.  Since this issue hasn't been resolved yet, I'm submitting a PR to remove `readLines`.  Happy to also use the first solution if it's needed for some other reason!
