### ISSUE TITLE
Updating datasets

### ISSUE THREAD

**Issue by isteves** [gaborcsardi/rcorpora#4]
Hi @gaborcsardi, I'd like to use the `dog_names` dataset from `corpora` , but I noticed it's not yet available through rcorpora.  I'm not sure if you already have some systematic way of updating it or if I should just submit a PR for dog_names.json/all the newest corpora files.  Let me know what works best for you!

corpora animals page: https://github.com/dariusk/corpora/tree/master/data/animals
rcorpora animals page: https://github.com/gaborcsardi/rcorpora/tree/master/inst/corpora/data/animals

**Comment by gaborcsardi** [comment]
The inst/corpora dir is the complete corpora repo, so I  just copy it in  there for an update. Then edit  DESCRIPTION, NEWS, update the README and that  should  be it. 

At least ideally, there must be a lot of new stuff now, so sg might break.

**Comment by gaborcsardi** [comment]
I'll update in a minute.

**Comment by gaborcsardi** [comment]
Done.
